"""Static site generation.

Takes validated ``ResumeData`` + a template id and writes a complete static
site: the template's fixed HTML/CSS plus a generated ``resume-data.js`` data
file and a ``.nojekyll`` marker. The template controls all layout; the data file
is the only part that varies per résumé.
"""

from __future__ import annotations

import json
import shutil
from pathlib import Path

from .schemas import ResumeData

ROOT = Path(__file__).resolve().parent.parent
TEMPLATES_DIR = ROOT / "templates"
SHARED_DIR = TEMPLATES_DIR / "_shared"

# template id -> human-readable metadata, surfaced to the frontend picker
TEMPLATES: dict[str, dict[str, str]] = {
    "engineer-clean": {
        "name": "Engineer Clean",
        "blurb": "Software / backend / AI engineers. Timeline + project cards.",
    },
    "research-academic": {
        "name": "Research Academic",
        "blurb": "PhD / research applicants. Publications front and center.",
    },
    "product-modern": {
        "name": "Product Modern",
        "blurb": "PMs / founders / generalists. Impact-led, bold hero.",
    },
}


class GenerationError(Exception):
    """Raised for an unknown template id or missing template files."""


def list_templates() -> list[dict[str, str]]:
    return [{"id": tid, **meta} for tid, meta in TEMPLATES.items()]


def _resume_data_js(data: ResumeData) -> str:
    payload = json.dumps(data.model_dump(), ensure_ascii=False, indent=2)
    return f"window.RESUME_DATA = {payload};\n"


def generate_site(data: ResumeData, template_id: str, out_dir: Path) -> Path:
    """Render ``data`` with ``template_id`` into ``out_dir``. Returns out_dir."""
    if template_id not in TEMPLATES:
        raise GenerationError(f"Unknown template '{template_id}'.")

    template_dir = TEMPLATES_DIR / template_id
    index_html = template_dir / "index.html"
    styles_css = template_dir / "styles.css"
    profile_svg = template_dir / "profile.svg"
    main_js = SHARED_DIR / "main.js"

    for required in (index_html, styles_css, profile_svg, main_js):
        if not required.exists():
            raise GenerationError(f"Template file missing: {required}")

    if out_dir.exists():
        shutil.rmtree(out_dir)
    assets = out_dir / "assets"
    assets.mkdir(parents=True)

    shutil.copyfile(index_html, out_dir / "index.html")
    shutil.copyfile(styles_css, assets / "styles.css")
    shutil.copyfile(profile_svg, assets / "profile.svg")
    shutil.copyfile(main_js, assets / "main.js")
    (assets / "resume-data.js").write_text(_resume_data_js(data), encoding="utf-8")

    # GitHub Pages: skip Jekyll processing so assets are served as-is.
    (out_dir / ".nojekyll").write_text("", encoding="utf-8")
    (out_dir / "README.md").write_text(
        "# Personal website\n\n"
        f"Generated by resume-site-tool using the `{template_id}` template.\n",
        encoding="utf-8",
    )
    # Marker so the tool can later tell which sites it manages.
    (out_dir / ".resume-site.json").write_text(
        json.dumps(
            {
                "generator": "resume-to-github-pages",
                "version": "0.1.0",
                "template": template_id,
            },
            indent=2,
        ),
        encoding="utf-8",
    )
    return out_dir
